services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
    command: "--web.enable-remote-write-receiver"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
